name: wordly
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  shared_preferences: ^2.5.3
  realm: ^20.1.1


  dio: ^5.9.0
  retrofit: ^4.7.1

  auto_route: ^10.1.2
  
  
  talker: ^4.9.3
  talker_flutter: ^4.9.3
  talker_dio_logger: ^4.9.3
  talker_bloc_logger: ^4.9.3


  package_info_plus: ^8.3.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.0
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.2
  retrofit_generator: ^9.0.0
  json_serializable: ^6.9.5


flutter:


  uses-material-design: true

  assets:
    - assets/pictures/
    - .env


  # мои шрифты думаю одного шрифта будет достаточно
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

